Work/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from extra_apps import xadmin
from django.views.static import serve
from Work.settings import MEDIA_ROOT, STATIC_ROOT
from django.conf.urls import url
from Work.views import page_not_found, page_error

urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    path('', include('apps.system.urls')),
    # 验证码
    path('captcha', include('captcha.urls')),
    path('users/', include('apps.users.urls')),
    # 添加media正则路径,显示图片用的
    # re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}, name='media'),
    # 静态文件映射
    url('^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}, name='static'),
]
handler404 = 'Work.views.page_not_found'
handler500 = 'Work.views.page_error'

apps/system/urls.py
from django.urls import path, re_path
from . import views

app_name = 'system'

urlpatterns = [
    path('', views.index, name='index'),
    # 控制台(所有用户)
    path('console/', views.ConsoleView.as_view(), name='console'),
    # 添加用户(超管)
    path('create_user/', views.CreateUserView.as_view(), name='create_user'),
    # 编辑用户(超管)
    path('update_info/', views.UpdateInfoView.as_view(), name='update_info'),
    # 个人信息(所有用户)
    path('my_info/', views.MyInfoView.as_view(), name='my_info'),
    # 学生列表(所有用户,超管&老师的权限高于学生)
    path('StudentList/', views.StudentListView.as_view(), name='StudentList'),
    # 删除的学生(老师)
    path('DelStudentList/', views.DelStudentListView.as_view(), name='DelStudentList'),
    # 发布作业
    path('PublishJob/', views.PublishJobView.as_view(), name='PublishJob'),
    # 检查作业
    path('CheckJobs/', views.CheckJobsView.as_view(), name='CheckJobs'),
    # 查看作业
    path('SeeJobs/', views.SeeJobsView.as_view(), name='SeeJobs'),
    # 上传文件
    path('UploadFiles/', views.UploadFilesView.as_view(), name='UploadFiles'),
    # 查看文件
    path('SeeFiles/', views.SeeFilesView.as_view(), name='SeeFiles'),
    # 下载文件
    re_path(r'^download/(?P<path>.*)$', views.download, name='download'),
    # 下载记录
    path('DownloadLog/', views.download_log, name='DownloadLog'),
]

apps/system/models.py
from django.db import models


# Create your models here.

# 任务文档(老师发布的任务)
class TeacherJobs(models.Model):
    T_title = models.CharField(max_length=200, verbose_name='任务标题')
    T_text = models.TextField(null=True, verbose_name='任务要求')
    T_count = models.IntegerField(verbose_name='完成人数', default=0)
    T_time = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    T_U = models.ForeignKey('users.User', on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = 'File_TeacherJobs'


# 上传的文件
class JobFiles(models.Model):
    J_name = models.CharField(max_length=200, verbose_name='文件名')
    J_files = models.FileField(upload_to='TeacherJobs', null=True, verbose_name='任务附件')
    J_T = models.ForeignKey('TeacherJobs', on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = 'File_JobFiles'


# 提交的任务(学生提交的作业)
class StudentJobs(models.Model):
    S_name = models.CharField(max_length=200, verbose_name='文件名')
    S_files = models.FileField(upload_to='StudentJobs', null=True, verbose_name='提交的任务')
    # 0已上传，1审核通过，2审核未通过
    S_is = models.IntegerField(verbose_name='是否通过', default=0)
    S_time = models.DateTimeField(auto_now_add=True, verbose_name='提交时间')
    S_num = models.FloatField(verbose_name='分数', null=True)
    # 关联老师的任务
    S_T = models.ForeignKey('TeacherJobs', on_delete=models.CASCADE, null=True)
    # 关联用户表
    S_U = models.ForeignKey('users.User', on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = 'File_StudentJobs'


# 文件共享(老师&学生分享的文件)
class FilesShare(models.Model):
    F_name = models.CharField(max_length=200, verbose_name='文件名')
    F_files = models.FileField(upload_to='FilesShare', null=True, verbose_name='文件共享')
    F_time = models.DateTimeField(auto_now_add=True, verbose_name='上传时间')
    F_U = models.ForeignKey('users.User', on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = 'File_FilesShare'


# 下载记录
class DownloadLog(models.Model):
    D_U = models.ForeignKey('users.User', on_delete=models.CASCADE, null=True)
    D_log = models.CharField(max_length=300)
    D_time = models.DateTimeField(auto_now_add=True, verbose_name='下载时间')

    class Meta:
        db_table = 'log_DownloadLog'

apps/system/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.http import JsonResponse, FileResponse
from django.contrib.auth.decorators import login_required
from apps.users.models import User
from apps.system.models import TeacherJobs, StudentJobs, JobFiles, FilesShare, DownloadLog
# 用户组&&权限
from django.contrib.auth.models import Group, Permission
from django.views import View
from django.utils.decorators import method_decorator
# 分页
from django.core.paginator import Paginator, PageNotAnInteger, InvalidPage
from django.core.cache import caches
# Q多条件查询
from django.db.models import Q, F
# 发送邮件脚本
from celery_tasks.email import send_email
# 短信脚本
from celery_tasks.phone import send_sms, get_code
from django.core.cache import cache
# 发邮件
from celery_tasks.email import send_email_code
# 上传文件存放目录
from Work.settings import MEDIA_ROOT
import json
import time


# Create your views here.

# 首页(所有用户)
@login_required
def index(request):
    if request.method == 'GET':
        return render(request, 'index.html')
    if request.is_ajax():
        # 当前密码
        password = request.POST.get('password')
        # 新密码
        new_password = request.POST.get('password1')
        # 第一道验证，验证当前用户密码
        ver = request.user.check_password(raw_password=password)
        if ver is True:
            return JsonResponse({'err': '200'})
        if new_password:
            # 修改当前用户的密码
            request.user.set_password(new_password)
            # 保存密码
            request.user.save()
            return JsonResponse({'err': 'update_yes'})
        else:
            return JsonResponse({'err': '100'})


# 用户列表tabs页面(超管)
@method_decorator(login_required, name='dispatch')
class ConsoleView(View):
    @staticmethod
    def get(request):
        trends = User.objects.all().order_by('-date_joined')
        user_list = User.objects.all()
        # 分页功能
        paginator = Paginator(user_list, 6)
        users = paginator.page(1)
        if request.is_ajax():
            page = request.GET.get('page')
            try:
                users = paginator.page(page)
            # 如果页数不是整数，返回第一页
            except PageNotAnInteger:
                users = paginator.page(1)
            # 如果页数不存在/不合法，返回最后一页
            except InvalidPage:
                users = paginator.page(paginator.num_pages)
            # 信息展出并转化为列表形式
            user_li = list(users.object_list.values())
            result = {'has_previous': users.has_previous(),
                      'has_next': users.has_next(),
                      'num_pages': users.paginator.num_pages,
                      'user_li': user_li}
            return JsonResponse(result)
        # 任务最新的一条
        jobs = TeacherJobs.objects.all().order_by('-T_time')
        now_job = jobs.first()
        # 任务量
        job_count = jobs.count()
        teachers = User.objects.filter(is_rank='教师').count()
        students = User.objects.filter(is_rank='学生').count()
        results = {'trends': trends, 'user_list': user_list, 'users': users, 'now_job': now_job, 'teachers': teachers,
                   'students': students, 'job_count': job_count}
        return render(request, 'system/console.html', results)

    @staticmethod
    def post(request):
        if request.is_ajax():
            # 启用/停用开关
            swi = request.POST.get('swi')
            # 删除的用户id
            del_user = request.POST.get('del_id')
            # 编辑用户的id
            update_id = request.POST.get('user_id')
            # 给redis等下修改页面来取,临时数据1分钟后清掉,以登录的用户名为键名
            if update_id:
                caches['redis_user'].set(request.user, update_id, 60)
                return JsonResponse({'update_id_info': 'ok'})
            # 搜索信息
            search = request.POST.get('search')
            if search:
                # Q多条件查询不区分大小写的所有包含有关的数据, 信息展出并转化为列表形式
                result = User.objects.filter(
                    Q(username__icontains=search) | Q(first_name__icontains=search) | Q(is_rank__icontains=search) | Q(
                        sex__icontains=search) | Q(phone=search) | Q(email=search))
                result = list(result.values())
                # print(result)
                return JsonResponse({'search_info': result})
            if del_user:
                User.objects.get(id=int(del_user)).delete()
                return JsonResponse({'del_info': 'del_ok'})
            # 代号1后的是id切片切出来
            swi_id = int(swi[1:])
            if swi[0] == '0':
                User.objects.filter(id=swi_id).update(is_active=0)
                return JsonResponse({'result': 'close'})
            else:
                User.objects.filter(id=swi_id).update(is_active=1)
                return JsonResponse({'result': 'open'})


# 添加用户页面(超管)
@method_decorator(login_required, name='dispatch')
class CreateUserView(View):
    @staticmethod
    def get(request):
        # 判断是否为超级用户
        if request.user.is_superuser is True:
            return render(request, 'system/create_user.html')
        else:
            return redirect('system:index')

    @staticmethod
    def post(request):
        if request.is_ajax():
            # 用户信息获取
            username = request.POST.get('username')
            first_name = request.POST.get('first_name')
            password1 = request.POST.get('password1')
            sex = request.POST.get('sex')
            city = request.POST.get('city')
            # 开关打开返回'on'，关闭返回None
            switch = request.POST.get('switch')
            # print(switch)
            # 判断用户是否存在
            try:
                user = User.objects.get(username=username)
            except Exception:
                user = None
            if user:
                return JsonResponse({'err': 'false'})
            if not all([username, password1, sex, city]):
                return JsonResponse({'err': '101'})
            # 如果未激活状态
            if switch is None:
                User.objects.create_user(username=username, first_name=first_name, password=password1, sex=sex,
                                         is_rank=city, is_active=0)
                return JsonResponse({'err': '200'})
            # 如果激活状态
            else:
                User.objects.create_user(username=username, first_name=first_name, password=password1, sex=sex,
                                         is_rank=city, is_active=1)
                return JsonResponse({'err': '200'})
        return render(request, 'system/create_user.html')


# 修改信息(超管编辑所有用户的信息)(超管)
@method_decorator(login_required, name='dispatch')
class UpdateInfoView(View):
    @staticmethod
    def get(request):
        try:
            if request.user.is_superuser is True:
                # 获取要修改的信息id
                user_id = caches['redis_user'].get(request.user)
                info = User.objects.get(id=int(user_id))
                # 先把信息存入session缓存中，因为session中的信息是安全的
                request.session['now_phone'] = info.phone
                return render(request, 'system/update_info.html', {'user': info})
            else:
                return redirect('system:index')
        except Exception:
            return redirect('system:index')

    @staticmethod
    def post(request):
        if request.is_ajax():
            user_id = request.POST.get('user_id')
            first_name = request.POST.get('first_name')
            sex = request.POST.get('sex')
            phone = request.POST.get('phone')
            email = request.POST.get('email')
            city = request.POST.get('city')
            # session获取当前的手机号
            now_phone = request.session.get('now_phone')
            # 临时删除当前手机号
            User.objects.filter(id=user_id).update(phone='')
            phone_is = User.objects.filter(Q(phone=phone)).count()
            # 判断手机号是否已经存在，如果存在恢复原来账号
            if phone_is >= 1:
                User.objects.filter(id=user_id).update(phone=now_phone)
                return JsonResponse({'update_info': 'phone_no'})
            else:
                User.objects.filter(id=user_id).update(first_name=first_name, sex=sex, phone=phone, email=email,
                                                       is_rank=city)
                return JsonResponse({'update_info': 'ok'})
        return render(request, 'system/update_info.html')


# 个人信息(每个用户修改个人信息)(所有用户)
@method_decorator(login_required, name='dispatch')
class MyInfoView(View):
    @staticmethod
    def get(request):
        teacher = TeacherJobs.objects.filter(T_U_id=request.user.id)
        student = StudentJobs.objects.filter(S_U_id=request.user.id)
        result = {'teacher': teacher, 'student': student}
        return render(request, 'system/my_info.html', result)

    @staticmethod
    def post(request):
        li = [request.user.phone]
        if request.is_ajax():
            # 手机绑定部分
            phone = request.POST.get('phone')
            phone_code = request.POST.get('phone_code')
            # 如果同时接收两个进行验证
            if phone and phone_code:
                code = cache.get(phone)
                # print(phone, code, phone_code)
                if phone_code == code:
                    # 验证通过，绑定成功
                    User.objects.filter(id=request.user.id).update(phone=phone)
                    return JsonResponse({'my_info': 'phone_ok'})
                else:
                    return JsonResponse({'my_info': 'phone_not'})
            if phone:
                # 临时删除当前手机号
                User.objects.filter(id=request.user.id).update(phone='')
                phone_is = User.objects.filter(Q(phone=phone)).count()
                if phone_is >= 1:
                    User.objects.filter(id=request.user.id).update(phone=li[0])
                    return JsonResponse({'my_info': 'phone_no'})
                else:
                    User.objects.filter(id=request.user.id).update(phone=li[0])
                    # 5分钟有效
                    is_code = get_code(6)
                    res = send_sms(phone, is_code)
                    cache.set(phone, is_code, 60 * 5)

templates/system/DelStudentList.html
{% extends 'system/StudentList.html' %}

{% block title %}
    删除的学生
{% endblock %}


{% block url %}
    <form action={% url 'system:DelStudentList' %}></form>
{% endblock %}


{% block btn_del %}
    <script type="text/html" id="toolbarDemo">
        <div class="layui-btn-container">
            <button class="layui-btn layui-btn-danger layui-btn-sm" lay-event="del_over">
                永久删除<span></span>
            </button>
            <button class="layui-btn layui-btn-sm" lay-event="getCheckLength" style="display: none">
                选了多少个？
            </button>
            <button class="layui-btn layui-btn-sm" lay-event="batch_recover">
                批量恢复<span></span>
            </button>
        </div>
    </script>
    <script type="text/html" id="barDemo">
        <a class="layui-btn layui-btn-xs" lay-event="recover">恢复</a>
    </script>
{% endblock %}

templates/system/StudentList.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    学生列表
{% endblock %}


{% block body %}
    <body>
    {#    搜索#}
    <div style="margin: 1%;">
        <label class="layui-form-label" style="display: none">搜索框</label>
        <div class="layui-input-inline">
            <input type="text" placeholder="请输入关键字搜索"
                   autocomplete="off" class="layui-input" style="border-radius: 15px;margin-left: 5%;" id="search">
        </div>
        <button type="button" class="layui-btn layui-btn-primary layui-btn-radius"
                style="margin-left: 1%" id="do_search">搜索
        </button>
        <button type="button" class="layui-btn layui-btn-primary layui-btn-radius" id="retreat" style="display: none">
            取消
        </button>
    </div>

    {#    表格#}
    {% block url %}
        <form action={% url 'system:StudentList' %}></form>
    {% endblock %}
    <table class="layui-hide" id="test" lay-filter="test"></table>
    {% if user.is_rank == '教师' or user.is_superuser == 1 %}
        {% block btn_del %}
            <script type="text/html" id="toolbarDemo">
                <div class="layui-btn-container">
                    <button class="layui-btn layui-btn-danger layui-btn-sm" lay-event="getCheckData">批量删除<span></span>
                    </button>
                    <button class="layui-btn layui-btn-sm" lay-event="getCheckLength" style="display: none">选了多少个？
                    </button>
                </div>
            </script>

            <script type="text/html" id="barDemo">
                <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
                <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
            </script>
        {% endblock %}
    {% else %}
        <script type="text/html" id="barDemo">
            <p>------</p>
        </script>
    {% endif %}
    </body>
{% endblock %}


{% block JS %}
    <script src={% static 'ajax/StudentList.js' %}></script>
{% endblock %}

templates/system/console.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    控制台
{% endblock %}


{% block CSS %}
    <style>
        .layui-table th, tr {
            text-align: center;
        }

        .layui-card-header {
            margin-top: 5%;
            background-color: #eee;
        }

        .layui-card-body {
            overflow: auto;
            height: 180px
        }
    </style>
    {% load set_set %}
{% endblock %}


{% block body %}
    <body>
    <div class="layui-tab layui-tab-brief" lay-filter="docDemoTabBrief">
        <ul class="layui-tab-title">
            <li class="layui-this">系统动态</li>
            {#    超管页面#}
            {% if user.is_superuser == 1 %}
                <li>管理中心</li>
            {% endif %}
            <li>世界</li>
        </ul>
        <div class="layui-tab-content">
            {#        系统动态#}
            <div class="layui-tab-item layui-show">
                <div class="layui-row">
                    {#                半左#}
                    <div class="layui-col-md6" style="padding-right: 2%; padding-left: 2%">
                        <div class="layui-col-md12">
                            <div class="layui-card">
                                <div class="layui-card-header">统计</div>
                                <div class="layui-card-body">
                                    <p>教师：<span style="color: #1c7430;font-size: 20px;">&emsp;{{ teachers }}&emsp;</span>名</p><br>
                                    <p>学生：<span style="color: #1c7430;font-size: 20px;">&emsp;{{ students }}&emsp;</span>名</p><br>
                                    <p>共计任务量：<span style="color: #1c7430;font-size: 20px;">&emsp;{{ job_count }}&emsp;</span>个</p>
                                </div>
                            </div>
                        </div>
                        <div class="layui-col-md12">
                            <div class="layui-card">
                                <div class="layui-card-header">当前任务<span>（已提交{{ now_job.T_count }}人）</span></div>
                                <div class="layui-card-body">
                                    <h2>{{ now_job.T_title }}</h2>
                                    <hr>
                                    {{ now_job.T_text|safe }}
                                </div>
                            </div>
                        </div>
                    </div>
                    {#                半右#}
                    <div class="layui-col-md6" style="padding-left: 2%;padding-right: 2%;">
                        <div class="layui-col-md12">
                            <div class='layui-card'>
                                <div class="layui-card-header">动态信息</div>
                                <div class="layui-card-body" style="height: 450px">
                                    <ul class="layui-timeline" style="padding-top: 1%">
                                        {% for users in trends %}
                                            <h3 class="layui-timeline-title">{{ users.date_joined|date:'Y-m-d'|set_set }}</h3>
                                            <li class="layui-timeline-item">
                                                <i class="layui-icon layui-timeline-axis">&#xe63f;</i>
                                                <div class="layui-timeline-content layui-text">
                                                    <p>
                                                        <i>{{ users.date_joined|date:"H:i:s" }}&emsp;</i>
                                                        <span style="color: #1c7430">{{ users.username }}({{ users.is_rank }})</span>成为AiYa的一员！
                                                    </p>
                                                </div>
                                            </li>
                                        {% endfor %}
                                        <li class="layui-timeline-item">
                                            <i class="layui-icon layui-anim layui-anim-rotate layui-anim-loop layui-timeline-axis"></i>
                                            <div class="layui-timeline-content layui-text">
                                                <div class="layui-timeline-title">更久前...Tao一直在忙着创造我...</div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {#        管理中心(超管页面)#}
            {% if user.is_superuser == 1 %}
                <div class="layui-tab-item">
                    <form class="layui-form" lay-filter="search" id="search">
                        <label class="layui-form-label" style="display: none">搜索框</label>
                        <div class="layui-input-inline" style="float:left;">
                            <input type="text" name="search" required lay-verify="empty_is" placeholder="请输入关键字搜索"
                                   autocomplete="off" class="layui-input" style="border-radius: 15px;margin-left: 5%;">
                        </div>
                        <button type="submit" lay-submit class="layui-btn layui-btn-primary layui-btn-radius"
                                style="margin-left: 1%">搜索
                        </button>
                        <button type="button" class="layui-btn layui-btn-primary layui-btn-radius" id="retreat">返回
                        </button>
                        <button type="button" class="layui-btn layui-btn-primary" style="float: right" id="add_user">
                            <i class="layui-icon"></i>添加用户
                        </button>
                    </form>
                    {#            管理表#}
                    <table class="layui-table">
                        <thead>
                        <tr>
                            <th>用户名</th>
                            <th>姓名</th>
                            <th>职位</th>
                            <th>性别</th>
                            <th>电话</th>
                            <th>邮箱</th>
                            <th>最近登录</th>
                            <th>更新时间</th>
                            <th>加入时间</th>
                            <th>启用/停用</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody id="tbody"></tbody>
                    </table>
                    {#           页码栏#}
                    <div style="position: absolute;bottom: 0;max-width: 1000px;width: 100%;left: 0;right: 0;margin: auto; display: block"
                         id="page_div">
                        <div style="text-align: center;margin: 5% 0;">
                            <form id="page" action={% url 'system:console' %}>
                                <a class="first_page">
                                    <button type="button" class="layui-btn layui-btn-primary layui-btn-sm">上一页</button>
                                </a>

                                {% for num in users.paginator.page_range %}
                                    <a class="now_page">
                                        <button type="button"
                                                class="layui-btn layui-btn-primary layui-btn-sm">{{ num }}</button>
                                    </a>
                                {% endfor %}

                                <button id="num_pages" type="button" class="layui-btn layui-btn-primary layui-btn-sm">
                                    共{{ users.paginator.num_pages }}页
                                </button>

                                <a class="last_page">
                                    <button type="button" class="layui-btn layui-btn-primary layui-btn-sm">下一页</button>
                                </a>
                            </form>
                        </div>
                    </div>
                </div>
            {% endif %}
            {#        世界#}
            <div class="layui-tab-item" style="text-align: center">
                <h1>计划所有用户聚集聊天！</h1>
                <h1>你好，世界！</h1>
                <h1>我还需要更深入的学习！</h1>
                <h1>加油！！</h1>
            </div>
        </div>
    </div>
    </body>
{% endblock %}


{% block JS %}
    <script src={% static 'ajax/console.js' %}></script>
{% endblock %}

templates/system/create_user.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    添加用户
{% endblock %}


{% block body %}
    <body>
    <div style="width: 50%; margin: 5% auto">
        <form class="layui-form" action={% url 'system:create_user' %}>
            {#        用户名，onkeyup不能出现中文#}
            <div class="layui-form-item">
                <label class="layui-form-label"><span style="color: red">*</span>用&ensp;户&ensp;名</label>
                <div class="layui-input-block">
                    <input type="text" name="username" required lay-verify="required|username|username_is"
                           placeholder="用户名必须在5~16位之间"
                           autocomplete="off" class="layui-input" style="width: 50%"
                           onkeyup="value=value.replace(/[\u4E00-\u9FA5]/g,'')">
                </div>
            </div>
            {#        真实姓名#}
            <div class="layui-form-item">
                <label class="layui-form-label"><span style="color: red">*</span>真实姓名</label>
                <div class="layui-input-block">
                    <input type="text" name="first_name" required lay-verify="required"
                           placeholder="请输入您的真实姓名"
                           autocomplete="off" class="layui-input" style="width: 50%">
                </div>
            </div>
            {#        密码1#}
            <div class="layui-form-item">
                <label class="layui-form-label"><span style="color: red">*</span>密&emsp;&emsp;码</label>
                <div class="layui-input-block">
                    <input type="password" name="password0" required lay-verify="required|password0"
                           placeholder="密码必须在6~10位之间"
                           autocomplete="off" class="layui-input" style="width: 50%">
                </div>
            </div>
            {#        密码2#}
            <div class="layui-form-item">
                <label class="layui-form-label"><span style="color: red">*</span>确认密码</label>
                <div class="layui-input-block">
                    <input type="password" name="password1" required lay-verify="required|password1|password_is"
                           placeholder="再次输入密码"
                           autocomplete="off"
                           class="layui-input" style="width: 50%">
                </div>
            </div>
            {#        性别#}
            <div class="layui-form-item">
                <label class="layui-form-label">性&emsp;&emsp;别</label>
                <div class="layui-input-block">
                    <input type="radio" name="sex" value="男" title="男" checked>
                    <input type="radio" name="sex" value="女" title="女">
                </div>
            </div>
            {#        职位#}
            <div class="layui-form-item">
                <label class="layui-form-label"><span style="color: red">*</span>职&emsp;&emsp;位</label>
                <div class="layui-input-inline">
                    <select name="city" lay-verify="required">
                        <option value=""></option>
                        <option value="教师">教师</option>
                        <option value="学生">学生</option>
                    </select>
                </div>
            </div>
            {#        状态#}
            <div class="layui-form-item">
                <label class="layui-form-label">状&emsp;&emsp;态</label>
                <div class="layui-input-block">
                    <input type="checkbox" name="switch" lay-skin="switch">
                </div>
            </div>
            {#        提交按钮#}
            <div class="layui-form-item" style="margin-top: 5%">
                <div class="layui-input-block">
                    <button type="submit" class="layui-btn" lay-submit lay-filter="add_user">确认添加</button>
                    <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                </div>
            </div>
        </form>
    </div>
    </body>
{% endblock %}


{% block JS %}
    <script>
        $(function () {
            layui.use('form', function () {
                let form = layui.form;

                // 监听提交
                form.on('submit(add_user)', function (data) {
                    // 表单数据
                    // console.log(data);
                    let url = $('form').attr('action');
                    $.ajax({
                        type: 'post',
                        url: url,
                        data: data.field,
                        success: function (res) {
                            if (res.err === 'false') {
                                // 自动获取错误焦点
                                $('input[name="username"]').addClass('layui-form-danger').focus();
                                layer.msg('该用户名已存在！', function () {
                                });
                                return false
                            }
                            if (res.err === '200') {
                                layer.msg('添加成功！');
                                $('button[type="reset"]').click();
                            } else {
                                console.log('失败！');
                            }
                        }
                    });
                    // 阻止页面跳转
                    return false;
                });
            });
        })
    </script>
{% endblock %}