Work/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from extra_apps import xadmin
from django.views.static import serve
from Work.settings import MEDIA_ROOT, STATIC_ROOT
from django.conf.urls import url
from Work.views import page_not_found, page_error

urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    path('', include('apps.system.urls')),
    # 验证码
    path('captcha', include('captcha.urls')),
    path('users/', include('apps.users.urls')),
    # 添加media正则路径,显示图片用的
    # re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}, name='media'),
    # 静态文件映射
    url('^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}, name='static'),
]
handler404 = 'Work.views.page_not_found'
handler500 = 'Work.views.page_error'

apps/system/urls.py
from django.urls import path, re_path
from . import views

app_name = 'system'

urlpatterns = [
    path('', views.index, name='index'),
    # 控制台(所有用户)
    path('console/', views.ConsoleView.as_view(), name='console'),
    # 添加用户(超管)
    path('create_user/', views.CreateUserView.as_view(), name='create_user'),
    # 编辑用户(超管)
    path('update_info/', views.UpdateInfoView.as_view(), name='update_info'),
    # 个人信息(所有用户)
    path('my_info/', views.MyInfoView.as_view(), name='my_info'),
    # 学生列表(所有用户,超管&老师的权限高于学生)
    path('StudentList/', views.StudentListView.as_view(), name='StudentList'),
    # 删除的学生(老师)
    path('DelStudentList/', views.DelStudentListView.as_view(), name='DelStudentList'),
    # 发布作业
    path('PublishJob/', views.PublishJobView.as_view(), name='PublishJob'),
    # 检查作业
    path('CheckJobs/', views.CheckJobsView.as_view(), name='CheckJobs'),
    # 查看作业
    path('SeeJobs/', views.SeeJobsView.as_view(), name='SeeJobs'),
    # 上传文件
    path('UploadFiles/', views.UploadFilesView.as_view(), name='UploadFiles'),
    # 查看文件
    path('SeeFiles/', views.SeeFilesView.as_view(), name='SeeFiles'),
    # 下载文件
    re_path(r'^download/(?P<path>.*)$', views.download, name='download'),
    # 下载记录
    path('DownloadLog/', views.download_log, name='DownloadLog'),
]

apps/users/urls.py
from django.urls import path, re_path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    # 注销
    path('logout/', views.off, name='logout'),
    # 邮件激活页面
    re_path('active/(?P<token>.*)$', views.active, name='active'),
]

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/base.html
<!DOCTYPE html>
<html lang="zh">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" href={% static 'img/favicon.ico' %}>
    <link rel="stylesheet" href={% static 'layui/css/layui.css' %}>
    {% block CSS %}{% endblock %}
</head>

{#主要部分#}
{#block中的内容是要替换的内容，之外的内容是继承使用的内容#}
{% block body %}
<body>
</body>
{% endblock %}

{#JS部分#}
<script src={% static 'layui/layui.js' %}></script>
<script src={% static 'jQuery/jquery-3.4.1.min.js' %}></script>
{#    验证js#}
<script src={% static 'ajax/verify.js' %}></script>
{% block JS %}{% endblock %}
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{#标题#}
{% block title %}
    哎吖任务发布系统
{% endblock %}

{#css部分#}
{% block CSS %}
    <style>
        .layui-layer-btn {
            text-align: center;
            border-top: 1px solid #eee;
        }
    </style>
{% endblock %}

{#body部分#}
{% block body %}
    <body class="layui-layout-body">
    <div class="layui-layout-admin">
        <div class="layui-header">
            <div class="layui-logo" style="color: white">
                <i class="layui-icon layui-icon-chart"></i>哎吖任务发布系统<i class="layui-icon layui-icon-chart"></i>
            </div>
            <!-- 头部区域（可配合layui已有的水平导航） -->
            <ul class="layui-nav layui-layout-left">
                <!--收缩侧边栏-->
                <li class="layui-nav-item" id="ss" style="cursor: pointer">
                    <i class="layui-icon layui-icon-shrink-right"></i>
                </li>
                <li class="layui-nav-item" id="ss_ss" style="display: none;cursor: pointer">
                    <i class="layui-icon layui-icon-spread-left"></i>
                </li>
                <!--刷新页面-->
                <li class="layui-nav-item" id="flush" style="margin: 0 30px; cursor: pointer">
                    <i class="layui-icon layui-icon-refresh"></i>
                </li>
                <li class="layui-nav-item layui-this" id="console">
                    <a href={% url 'system:console' %}>控制台</a>
                </li>
            </ul>
            <ul class="layui-nav layui-layout-right">
                <li class="layui-nav-item">
                    {% if user.is_rank is None %}
                        <a href="javascript:">
                            <img class="layui-nav-img" alt="头像" src={% static 'img/gif3.gif' %}>
                            {{ user }}(超级管理员)
                        </a>
                    {% else %}
                        <a href="javascript:">
                            <img class="layui-nav-img" alt="头像" src={% static 'img/gif3.gif' %}>
                            {{ user }}({{ user.is_rank }})
                        </a>
                    {% endif %}
                    <dl class="layui-nav-child">
                        <dd><a href="javascript:" id="user_info">基本资料</a></dd>
                        <dd><a href="javascript:" id="update_pwd">修改密码</a></dd>
                    </dl>
                </li>
                <li class="layui-nav-item">
                    <a href="javascript:">帮助</a>
                    <dl class="layui-nav-child" id="help">
                        <dd><a href="javascript:" id="system_info">系统介绍</a></dd>
                        <dd><a href="javascript:" id="WeChat">联系作者</a></dd>
                    </dl>
                </li>
                <li class="layui-nav-item"><a href={% url 'users:logout' %}>
                    注销&ensp;<i class="layui-icon layui-icon-logout"></i></a></li>
            </ul>
        </div>

        <div class="layui-side layui-bg-black" id="left">
            <div class="layui-side-scroll">
                <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
                <ul class="layui-nav layui-nav-tree  layui-anim layui-anim-up" lay-filter="test" id="nav_left">
                    <li class="layui-nav-item">
                        <a href="javascript:">个人信息</a>
                        <dl class="layui-nav-child">
                            <dd><a id="my_info" href={% url 'system:my_info' %}>个人&任务</a></dd>
                        </dl>
                    </li>
                    <li class="layui-nav-item">
                        <a href="javascript:">学生信息</a>
                        <dl class="layui-nav-child">
                            <dd><a href={% url 'system:StudentList' %}>学生列表</a></dd>
                        </dl>
                    </li>
                    <li class="layui-nav-item">
                        <a href="javascript:">任务中心</a>
                        <dl class="layui-nav-child">
                            {% if request.user.is_superuser == 1 or request.user.is_rank == '教师' %}
                                <dd><a href={% url 'system:PublishJob' %}>发布作业</a></dd>
                                <dd><a href="{% url 'system:CheckJobs' %}">检查作业</a></dd>
                                <dd><a href="{% url 'system:SeeJobs' %}">查看作业</a></dd>
                            {% else %}
                                <dd><a href="{% url 'system:SeeJobs' %}">查看作业</a></dd>
                            {% endif %}
                        </dl>
                    </li>
                    <li class="layui-nav-item">
                        <a href="javascript:">文件中心</a>
                        <dl class="layui-nav-child">
                            <dd><a href="{% url 'system:SeeFiles' %}">查看文件</a></dd>
                            <dd><a href="{% url 'system:UploadFiles' %}">上传文件</a></dd>
                            <dd><a href="{% url 'system:DownloadLog' %}">下载记录</a></dd>
                        </dl>
                    </li>
                    <li class="layui-nav-item">
                        {% if request.user.is_superuser == 1 or request.user.is_rank == '教师' %}
                            <a href="javascript:">学生管理</a>
                            <dl class="layui-nav-child">
                                <dd><a href={% url 'system:DelStudentList' %}>删除的学生</a></dd>
                            </dl>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>

        <div class="layui-body">
            <!-- 内容主体区域 -->
            <iframe class="layui-col-md12" height="100%" width="100%" src={% url 'system:console' %}></iframe>
        </div>

        <div class="layui-footer" style="text-align: center;background-color: #ffffff;">
            <!-- 底部固定区域 -->
            © AiYa - 任务发布系统
        </div>
    </div>
    </body>
    <div style="padding: 50px; line-height: 22px; background-color: #eee; font-weight: 600; display: none" id="info">
        <h2>基本资料</h2>
        <hr>
        <br><br>用&ensp;户&ensp;名：{{ user }}
        <br><br>姓&emsp;&emsp;名：{{ user.first_name }}
        <br><br>身&emsp;&emsp;份：{{ user.is_rank }}
        <br><br>性&emsp;&emsp;别：{{ user.sex }}
        <br><br>邮&emsp;&emsp;箱：{{ user.email }}
        <br><br>手&ensp;机&ensp;号：{{ user.phone }}
        <br><br>最近登录：{{ user.last_login|date:'Y-m-d H:i:s' }}
        <br><br>加入时间：{{ user.date_joined|date:'Y-m-d H:i:s' }}
    </div>
    <img alt="二维码" id="WeChat_code" width="400" height="500" style="display: none" src={% static 'img/WeChat.jpg' %}>
    <form style="display: none" action={% url 'system:index' %}>
        <div style="margin: 10% 10% 10% 0;" class="layui-form" lay-filter="up_pwd">
            {#        密码1#}
            <div class="layui-form-item">
                <label class="layui-form-label">新&ensp;密&ensp;码</label>
                <div class="layui-input-block">
                    <input type="password" name="password0" required lay-verify="required|password0"
                           placeholder="密码必须在6~10位之间"
                           autocomplete="off"
                           class="layui-input">
                </div>
            </div>
            {#        密码2#}
            <div class="layui-form-item">
                <label class="layui-form-label">确认密码</label>
                <div class="layui-input-block">
                    <input type="password" name="password1" required lay-verify="required|password1|password_is"
                           placeholder="再次输入密码"
                           autocomplete="off"
                           class="layui-input">
                </div>
            </div>
            {#        提交#}
            <div style="text-align: center;margin-top: 10%;">
                <button type="submit" class="layui-btn layui-btn-primary layui-btn-radius" lay-submit>确认修改</button>
            </div>
        </div>
    </form>
{% endblock %}

{#js部分#}
{% block JS %}
    <script src={% static 'ajax/index.js' %}></script>
{% endblock %}